# Site settings
title: GDSC Seoultech
email: twinklesu914@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url: twinklesu.github.io # the base hostname & protocol for your site
github_username:  twinklesu

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path/


