# Site settings
name: Subin
email: twinklesu914@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "숩니의 꼼지락 개발 블로그"
permalink: pretty
baseurl: ""

# social
github:
  username: twinklesu

instagram:
  username: twinklesu14
